Repository shimming-toolbox/helpDocMd, pull requests merged in 2020-06, with the labels that each got.

#3 Fix crash when no class folder : Fix #2
  src/@Documentor/autoassigndocfiles.m
  src/fUtilities/parent.m
Labels: bug

#9 Rt/7 packages
  src/+valid/mustBeA.m
  src/+valid/mustBeBoolean.m
  src/+valid/mustBeFile.m
  src/+valid/mustBeFileOrFolder.m
  src/+valid/mustBeFolder.m
  src/+valid/mustBeString.m
  src/+valid/mustBeStringOrChar.m
  src/+valid/mustBeStringOrCharOrCellstr.m
  src/+valid/mustBeStringScalarOrCharVector.m
  src/@Advisor/readme.m
  src/@Advisor/txttable.m
  src/@Documentor/Documentor.m
  src/@Documentor/autoassigndocfiles.m
  src/@Documentor/documentclassdef.m
  src/@Documentor/documentclassmethods.m
  src/@Documentor/documentclassproperties.m
  src/@Documentor/findfiles.m
  src/@Documentor/mustBeDocumentable.m
  src/@Documentor/printYml.m
  src/@Documentor/printdoc.m
  src/@Examiner/Examiner.m
  src/@Examiner/extracthelpbody.m
  src/@Examiner/extracthelpheader.m
  src/@Examiner/gethelptext.m
  src/@Examiner/getmattributes.m
  src/@Examiner/mfiletype.m
  src/@Examiner/unpack.m
  src/fUtilities/@Pathologist/Pathologist.m
  src/fUtilities/@Pathologist/abs.m
  src/fUtilities/@Pathologist/mapdirectorytree.m
  src/fUtilities/@Pathologist/typecast.m
  src/fUtilities/@Pathologist/whatr.m
  src/fUtilities/abspath.m
  src/fUtilities/findfiles.m
  src/fUtilities/parent.m
Labels: enhancement

#18 Replace todo.m with GitHub issues (#14-17)
  docs/todo.md
  src/todo.m
Labels: documentation
